name: 'laravel-ms-rabbitmq'

volumes:
  main-dbdata:
  admin-dbdata:
services:
  main_db:
    container_name: node-maindb
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=admin123
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin123
      - MARIADB_DATABASE=main_db
    volumes:
      - main-dbdata:/var/lib/mysql
  main_app:
    build:
      context: .
      dockerfile: main-app.dockerfile
    container_name: node-mainapp
    depends_on:
      - main_db
    ports:
      - 8081:8000

  admin_app:
    build:
      context: .
      dockerfile: admin-app.dockerfile
    container_name: node-adminapp
    depends_on:
      - admin_db
    ports:
      - 8080:8000
  admin_db:
    container_name: node-admindb
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=admin123
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin123
      - MARIADB_DATABASE=admin_db
    volumes:
      - admin-dbdata:/var/lib/mysql
  
  rabbitmq_svc:
    image: rabbitmq:3-alpine
    container_name: rabbitmq-service
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/