name: 'main-app'

services:
  main_db:
    container_name: node-maindb
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=admin123
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin123
      - MARIADB_DATABASE=main_db
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 6034:3306