name: 'admin-app'

services:
  # admin:
  #   container_name: node-admin
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - admin_db
  #   volumes:
  #     - .:/app
    
  admin_db:
    container_name: node-admindb
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=admin123
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin123
      - MARIADB_DATABASE=admin_db
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 6033:3306